trigger: none
#pipeline kab chalegi

pool: pool
# agent pool ka naam, jaha par agent configure hai, or jaha pipeline chalegi

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Demo-Service-Connection'
    backendAzureRmStorageAccountName: 'mystorage836753'
    backendAzureRmContainerName: 'mystorage836753'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Demo-Service-Connection'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Demo-Service-Connection'