trigger: none
#pipeline kab chalega

pool: pool
#pipeline kaha chalega, kis agent me chalega

 
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Demo-Service-Connection'
    backendAzureRmStorageAccountName: 'mystorage836753'
    backendAzureRmContainerName: 'mystorage836753'
    backendAzureRmKey: 'statefile'

