trigger: none

pool: demo_agent_pool

jobs:
  - job: Init_validate_scanning
    displayName: Terraform init, validate tfsec scan
    steps:
      
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Demo-Service-Connection'
          backendAzureRmStorageAccountName: 'mystorage836753'
          backendAzureRmContainerName: 'mystorage836753'
          backendAzureRmKey: 'demostatefile1'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
      - task: tfsec@1
        inputs:
          version: 'v1.26.0'
    
  - job:   
    displayName: terraform plan
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Demo-Service-Connection'
          backendAzureRmStorageAccountName: 'mystorage836753'
          backendAzureRmContainerName: 'mystorage836753'
          backendAzureRmKey: 'demostatefile1'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'Demo-Service-Connection'