trigger: none
pool: demo_agent_pool
steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Demo-Service-Connection'
      backendAzureRmStorageAccountName: 'mystorage836753'
      backendAzureRmContainerName: 'mystorage836753'
      backendAzureRmKey: 'terraformfile'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'Demo-Service-Connection'
  - task: tfsec@1
    inputs:
      version: 'v1.26.0'